# Generated by Django 6.0.3 on 2026-03-30 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReplanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(default=django.utils.timezone.localdate)),
                ('trigger_type', models.CharField(choices=[('add_event', 'Add Event'), ('task_done', 'Task Done'), ('change_estimate', 'Change Estimate'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('trigger_payload_json', models.JSONField(blank=True, default=dict)),
                ('old_version', models.PositiveIntegerField(default=0)),
                ('new_version', models.PositiveIntegerField(default=0)),
                ('moved_block_count', models.PositiveIntegerField(default=0)),
                ('summary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_name', models.CharField(blank=True, max_length=120)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveIntegerField(default=60)),
                ('scheduled_minutes', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('assignment', 'Assignment'), ('project', 'Project'), ('exam', 'Exam'), ('reading', 'Reading'), ('meeting', 'Meeting'), ('other', 'Other')], default='assignment', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('source', models.CharField(default='manual', max_length=30)),
                ('extraction_confidence', models.FloatField(default=1.0)),
                ('raw_excerpt', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('carry_over_count', models.PositiveIntegerField(default=0)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_datetime', '-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('preferred_study_start', models.TimeField(default='09:00')),
                ('preferred_study_end', models.TimeField(default='21:00')),
                ('sleep_start', models.TimeField(default='23:30')),
                ('sleep_end', models.TimeField(default='07:30')),
                ('breakfast_start', models.TimeField(default='08:00')),
                ('breakfast_end', models.TimeField(default='08:30')),
                ('lunch_start', models.TimeField(default='12:00')),
                ('lunch_end', models.TimeField(default='13:00')),
                ('dinner_start', models.TimeField(default='18:00')),
                ('dinner_end', models.TimeField(default='19:00')),
                ('max_continuous_work_minutes', models.PositiveIntegerField(default=120)),
                ('default_break_minutes', models.PositiveIntegerField(default=15)),
                ('freeze_horizon_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('class', 'Class'), ('meeting', 'Meeting'), ('routine', 'Routine'), ('deadline', 'Deadline'), ('other', 'Other')], default='class', max_length=20)),
                ('is_fixed', models.BooleanField(default=True)),
                ('source', models.CharField(default='ics', max_length=30)),
                ('external_uid', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_datetime'],
                'constraints': [models.UniqueConstraint(fields=('external_uid', 'start_datetime'), name='planner_unique_external_uid_start')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('block_type', models.CharField(choices=[('task', 'Task'), ('class', 'Class'), ('meeting', 'Meeting'), ('sleep', 'Sleep'), ('meal', 'Meal'), ('break', 'Break'), ('other', 'Other')], default='task', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_locked', models.BooleanField(default=False)),
                ('source', models.CharField(default='scheduler', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.task')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
